name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
        redis:
            image: redis:alpine3.21
            ports:
              - 6379:6379
            options: >-
              --health-cmd "redis-cli ping"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
        postgres:
            image: postgres:17-alpine
            ports:
              - 5432:5432
            env:
              POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
              POSTGRES_USER: ${{ secrets.DB_USER }}
              POSTGRES_DB: ${{ secrets.DB_NAME }}
            options: >-
              --health-cmd "pg_isready -U postgres"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
    env:
        SPRING_PROFILES_ACTIVE: test
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: 5432
        DB_HOST: localhost
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
        STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 24
          uses: actions/setup-java@v4.7.1
          with:
            distribution: 'temurin'
            java-version: '24'
            cache: maven

        - name: Build maven project
          run: mvn -B clean package --file pom.xml
    
        - name: Run tests
          run: mvn test -Dspring.profiles.active=test